Update ex.yml

diff --git a/.github/workflows/ex.yml b/.github/workflows/ex.yml
--- a/.github/workflows/ex.yml
+++ b/.github/workflows/ex.yml
@@ -28,7 +28,7 @@ env:
   WORKSPACE: ${{ github.workspace }}
   CIC_TCI_CLIENTID_CICD: ${{ secrets.DEV_TCI_CLIENT_ID }}
   CIC_TCI_CLIENTSECRET_CICD: ${{ secrets.DEV_TCI_CLIENT_SECRET }}
-  BRANCH_NAME: ${{ github.event.inputs.branch_name }}
+  #BRANCH_NAME: ${{ github.event.inputs.branch_name }}
   REPONAME: ${{ github.event.repository.name }}
 
 jobs:
@@ -44,13 +44,13 @@ jobs:
         run: |
           git config --global --add safe.directory /__w/${REPONAME}/${REPONAME}
           
-      - name: Checkout
-        uses: actions/checkout@v2.3.4
-        with:
-          fetch-depth: 0
-          submodules: 'true'
-          ref: ${{ env.BRANCH_NAME }}
-          token: ${{ env.GITHUB_PAT }}
+    #  - name: Checkout
+    #    uses: actions/checkout@v2.3.4
+    #    with:
+    #      fetch-depth: 0
+    #      submodules: 'true'
+    #      ref: ${{ env.BRANCH_NAME }}
+    #      token: ${{ env.GITHUB_PAT }}
 
       - name: CHC-App-Restart
         uses: actions/checkout@v2.3.4
@@ -74,34 +74,6 @@ jobs:
         id: determine_action
         run: echo "::set-output name=command::$(echo ${{ github.event.inputs.command }} | tr '[:upper:]' '[:lower:]')"
 
-      - name: Execute action
-        env:
-           FILE: application_name.txt
-        run: |
-          cd $WORKSPACE
-          export DEPLOYMENT_SCRIPT=${WORKSPACE}/CHC_Restart/cicd-scripts/TCI-Deployment/bin/tci
-          echo ${{ github.event.inputs.application_name }}
-          ls ${DEPLOYMENT_SCRIPT}
-          action=$(echo "${{ steps.determine_action.outputs.command }}")
-          for i in `cat $FILE`; do 
-           case $action in
-            start)
-             #bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh scale $i ${{ github.event.inputs.instance_count }}
-              bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh start $i
-              ;;
-            stop)
-              bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh stop $i
-              ;;
-            scale)
-              bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh scale $i ${{ github.event.inputs.instance_count }}
-              ;;
-            *)
-              echo "Invalid action provided: $action"
-              exit 1
-              ;;
-           esac
-          done
-        
       - name: Generate tibco token
         run: |
           response="$(
@@ -115,7 +87,39 @@ jobs:
           sudo su
           cd ${WORKSPACE}/CHC_Restart/cicd-scripts/
           ./tibcli authorize --token $TCI_TOKEN
-          ./tibcli app scaleto 0 bw.mc-files-confirmedPO
+       #   ./tibcli app scaleto 0 bw.mc-files-confirmedPO
+
+      - name: Execute action
+        env:
+           FILE: application_name.txt
+        run: |
+          cd $WORKSPACE
+          #export DEPLOYMENT_SCRIPT=${WORKSPACE}/CHC_Restart/cicd-scripts/TCI-Deployment/bin/tci
+          echo ${{ github.event.inputs.application_name }}
+          #ls ${DEPLOYMENT_SCRIPT}
+          action=$(echo "${{ steps.determine_action.outputs.command }}")
+          for i in `cat $FILE`; do 
+           case $action in
+            start)
+             #bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh scale $i ${{ github.event.inputs.instance_count }}
+             #bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh start $i
+              ./tibcli app scaleto 1 ${{ github.event.inputs.instance_count }} $i
+              ;;
+            stop)
+              #bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh stop $i
+              ./tibcli app scaleto 0 ${{ github.event.inputs.instance_count }} $i
+              ;;
+            scale)
+              #bash ${DEPLOYMENT_SCRIPT}/chc-app-manage2.sh scale $i ${{ github.event.inputs.instance_count }}
+              ./tibcli app scaleto ${{ github.event.inputs.instance_count }} $i
+              ;;
+            *)
+              echo "Invalid action provided: $action"
+              exit 1
+              ;;
+           esac
+          done
+        
           
       #- name: Authorize tibcli
         #run: |
